version: 2.1

executors:
  golang:
    working_directory: /go/src/moul.io/golang-repo-template
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"
      DOCKER_IMAGE: moul/golang-repo-template

commands:
  install-retry:
    steps:
      - run: command -v wget &>/dev/null && wget -O /tmp/retry "https://github.com/moul/retry/releases/download/v0.5.0/retry_$(uname -s)_$(uname -m)" || true
      - run: if [ ! -f /tmp/retry ]; then command -v curl &>/dev/null && curl -L -o /tmp/retry "https://github.com/moul/retry/releases/download/v0.5.0/retry_$(uname -s)_$(uname -m)"; fi
      - run: chmod +x /tmp/retry
      - run: /tmp/retry --version
  install-golangci-lint:
    steps:
      - run: /tmp/retry -m 3 curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.15.0

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  go-build:
    executor: golang
    steps:
      - checkout
      - install-retry
      - run: /tmp/retry -m 3 go mod download
      - run: /tmp/retry -m 3 make install
      - run: /tmp/retry -m 3 make test
      - install-golangci-lint
      - run: PATH=$PATH:$(pwd)/bin /tmp/retry -m 3 make lint
      - codecov/upload:
          file: coverage.txt

  docker-build:
    executor: golang
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - install-retry
      - run: /tmp/retry -m 3 docker build -t ${DOCKER_IMAGE} .

workflows:
  main:
    jobs:
      - go-build
      - docker-build
